config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "coroas#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :coroas, only: [:index]
  resources :pedidos, only: [:new, :create, :show, :index] do
    resources :pagamentos, only: [:edit]
  end
  resources :pagamentos, only: [:show, :update]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coroa.rb
class Coroa < ApplicationRecord
  has_many :pedidos
end

app/models/entrega.rb
class Entrega < ApplicationRecord
  has_many :pedidos
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
  has_many :pedidos
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :coroa
  belongs_to :velorio
  belongs_to :pagamento
  belongs_to :entrega
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pedidos
end

app/models/velorio.rb
class Velorio < ApplicationRecord
  has_many :pedidos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/coroas_controller.rb
class CoroasController < ApplicationController

  def index
    @coroas = Coroa.all
  end

  def create
    @coroa = current_user.build_coroa(coroa_params)

    if @coroa.save
      redirect_to coroa_path(@coroa), notice: 'coroa inserida com sucesso'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def coroa_params
    params.require(:coroa).permit(:codigo, :descricao, :preco_em_centavos)
  end
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController

  def edit
    @pagamento = Pagamento.find(params[:id])
  end

  def update
    @pagamento = Pagamento.find(params[:id])
    @pagamento.status = "Processando pagamento"

    if @pagamento.update(pagamento_params)
      redirect_to pedidos_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def pagamento_params
    params.require(:pagamento).permit(:tipo, :parcelas, :identificador, :card_token)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  def index
    @pedidos = Pedido.all
  end

  def new
    @pedido = Pedido.new
    @velorios = Velorio.all
    @pagamentos = Pagamento.all
    @coroa = Coroa.find(params[:coroa_id])
  end

  def create
    @pedido = Pedido.new(pedido_params)
    @velorios = Velorio.all
    @coroa = Coroa.find(params[:pedido][:coroa_id])

    @pedido.user = current_user
    @pedido.coroa_id = params[:pedido][:coroa_id]
    @entrega = Entrega.new(status: "Aguardando Pagamento")
    @pagamento = Pagamento.new(status: "Aguardando Pagamento")

    @pedido.pagamento = @pagamento
    @pedido.entrega = @entrega

    if @pedido.save
      @pagamento.save
      @entrega.save
      redirect_to edit_pedido_pagamento_path(@pedido, @pagamento), notice: 'pedido inserido com sucesso'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def pedido_params
    params.require(:pedido).permit(:nome_falecido, :data_velorio, :velorio_id, :faixa, :coroa_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coroas/index.html.erb
<h1>Lista das Coroas</h1>

<% @coroas.each do |coroa| %>

  <% valor = coroa.preco_em_centavos / 100 %>
  <% centavos = coroa.preco_em_centavos % 100 %>
  <% centavos_formatados = centavos < 10 ? "0#{centavos}" : centavos %>

  <p>
    <strong>Código:</strong> <%= coroa.codigo %><br>
    <strong>Descrição:</strong> <%= coroa.descricao %><br>
    <strong>Valor:</strong> R$<%= "#{valor},#{centavos_formatados}" %><br>
    <strong><%= link_to 'Comprar', new_pedido_path(coroa_id: coroa.id), class: 'btn btn-primary' %></strong>
  </p>

<% end %>
    <%= link_to "Sair", destroy_user_session_path, data: {turbo_method: :delete} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homenageie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pagamentos/edit.html.erb
<%= simple_form_for [@pagamento] do |f| %>

        <%= f.input :tipo, label: false, placeholder: "Tipo" %>

        <%= f.input :parcelas, label: false, placeholder: "Quantidade de parcelas" %>

        <%= f.input :identificador, label: "Identificador" %>

        <%= f.input :status, label: "Status" %>

        <%= f.text_field :card_token %>

        <%= f.submit 'Pagar', class: 'btn btn-primary' %>

      <% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pedidos/index.html.erb
<h1>Lista das Pedidos</h1>

<% @pedidos.each do |pedido| %>

<div style="border: 2px solid #000; padding: 20px;">
  <% valor = pedido.coroa.preco_em_centavos / 100 %>
  <% centavos = pedido.coroa.preco_em_centavos % 100 %>
  <% centavos_formatados = centavos < 10 ? "0#{centavos}" : centavos %>

  <p>
    <strong>Nome do Falecido:</strong> <%= pedido.nome_falecido %><br>
    <strong>Faixa:</strong> <%= pedido.faixa %><br>
    <strong>Endereço:</strong> <%= pedido.velorio.nome %><br>

    <strong>Código:</strong> <%= pedido.coroa.codigo %><br>
    <strong>Descrição:</strong> <%= pedido.coroa.descricao %><br>
    <strong>Valor:</strong> R$<%= "#{valor},#{centavos_formatados}" %><br>

    <strong>Pagamento ID:</strong> <%= pedido.pagamento.id %><br>
    <strong>Pagamento Tipo:</strong> <%= pedido.pagamento.tipo %><br>
    <strong>Pagamento Status:</strong> <%= pedido.pagamento.status %><br>

    <strong>Entrega ID:</strong> <%= pedido.entrega.id %><br>
    <strong>Entrega Status:</strong> <%= pedido.entrega.status %><br>

    <% if pedido.pagamento.status == "Aguardando Pagamento" %>
      <strong><%= button_to 'Pagar', edit_pedido_pagamento_path(pedido, pedido.pagamento), method: :get, class: 'btn btn-primary' %></strong>
      
    <% end %>
  </p>
</div>

<% end %>

app/views/pedidos/new.html.erb
<%= simple_form_for [@pedido] do |f| %>

        <%= f.input :nome_falecido, label: false, placeholder: "Nome do Falecido" %>

        <%= f.input :faixa, label: false, placeholder: "Frase para a faixa da coroa" %>

        <%= f.collection_select :velorio_id, @velorios, :id, :nome, { include_blank: 'Selecione o velório' } %>

        <%= f.input :data_velorio, order: [:day, :month, :year], use_month_numbers: true, start_year: Time.now.year, end_year: Time.now.year + 1, label: "Data" %>

        <%= f.text_field :coroa_id, value: @coroa.id %>

        <%= f.submit 'Ir para pagamento', class: 'btn btn-primary' %>

      <% end %>